### ISSUE TITLE
Completion box item background is hard to see

### ISSUE THREAD

**Issue by RUSshy** [graceful-potato/gruvbox-ish#1]
![image](https://user-images.githubusercontent.com/18348637/97809171-a9284880-1c6b-11eb-928c-d0b409b9daee.png)

As you can see the background of the selected item is hard to see

Wich makes it hard to choose the right the completion item

**Comment by RUSshy** [comment]
Here is what needs to be edited:

```json
"editorSuggestWidget.background": "#",// widget bg
"editorSuggestWidget.selectedBackground": "#",// <-- this one -->
"editorSuggestWidget.highlightForeground": "#",// typed(matching) symbols color
```

**Comment by graceful-potato** [comment]
Thanks, will check it soon

**Comment by RUSshy** [comment]
Thanks, i love your theme, nice job!

**Comment by graceful-potato** [comment]
I think should be better now, let me know is it ok or no
