### ISSUE TITLE
`list.focusBackground` was renamed to `quickInput.list.focusBackground` in VSCode 1.54.0

### ISSUE THREAD

**Issue by singularitti** [graceful-potato/gruvbox-ish#3]
According to its [release notes](https://code.visualstudio.com/updates/v1_54), the `list.focusBackground` was renamed to `quickInput.list.focusBackground` [in VSCode 1.54.0](https://github.com/microsoft/vscode/commit/4a941b1853a7b9e0173fd3f9c6eeeb6af13503f0#diff-f264602aa6d3cb74d6e344ffe88192b001c1611314325bad2b4f2cfa58b62031).

![image](https://user-images.githubusercontent.com/25192197/110031178-951d5200-7d04-11eb-8eeb-cc8aab2df9e0.png)

I don't know for sure, but it seems to break the coloring of the command panel's selection:

![image](https://user-images.githubusercontent.com/25192197/110031345-cbf36800-7d04-11eb-9248-9dc20d651708.png)

Before this release it was brown, but now it is blue. Could you change the [corresponding line](https://github.com/graceful-potato/gruvbox-ish/blob/819190140ae3d8974dd2e036392b9e16d6c0cca2/themes/gruvbox-ish-dark-medium.json#L103)?

**Comment by graceful-potato** [comment]
Thanks! Fixed and pushed new version to marketplace.
