### ISSUE TITLE
Windows Terminal

### ISSUE THREAD

**Issue by ghost** [graceful-potato/gruvbox-ish#5]
It would be nice to see this theme for Windows Terminal. Is it possible?

**Comment by graceful-potato** [comment]
I am pretty sure you can find regular gruvbox theme for windows terminal. Its not that different from this one.

**Comment by ghost** [comment]
In your colorscheme, the colors are a little different

![1](https://user-images.githubusercontent.com/87933754/129471939-629c23d7-ac14-4191-91de-067c5169a973.png)

than in the original Gruvbox

![2](https://user-images.githubusercontent.com/87933754/129471930-86dbe06a-b5c0-4aa7-8614-aef74d17dc6f.png)

**Comment by graceful-potato** [comment]
You can take colors from [here](https://github.com/graceful-potato/gruvbox-ish/blob/2a3ce627fa616b354d1b4c8fbb5225064c43516c/themes/gruvbox-ish-dark-medium.json#L161-L178)

**Comment by ghost** [comment]
Thanks!

```json
{
    "name": "Gruvbox Ish Hard",

    "cursorColor": "#dfbf8e",
    "selectionBackground": "#928374",

    "background": "#1d2021",
    "foreground": "#dfbf8e",

    "black": "#32302f",
    "red": "#d75f5f",
    "green": "#a8a81c",
    "yellow": "#d69617",
    "blue": "#458588",
    "purple": "#b16286",
    "cyan": "#689d6a",
    "white": "#a89984",

    "brightBlack": "#928374",
    "brightRed": "#d75f5f",
    "brightGreen": "#8b9553",
    "brightYellow": "#cea64a",
    "brightBlue": "#83a598",
    "brightPurple": "#d3869b",
    "brightCyan": "#87af87",
    "brightWhite": "#dfbf8e"
}
```
